version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install -g aws-cdk
      - npm install

  pre_build:
    commands:
      - echo Pre-build phase started on `date`
      - echo Logging in to Amazon ECR...

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Next.js application...
      - npm run build
      - echo Deploying with CDK...
      - npx cdk deploy --require-approval never

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: out
