export const countries = [
  { code: 'US', name: 'United States', flag: '🇺🇸' },
  { code: 'JP', name: 'Japan', flag: '🇯🇵' },
  { code: 'DE', name: 'Germany', flag: '🇩🇪' },
  { code: 'FR', name: 'France', flag: '🇫🇷' },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧' },
  { code: 'IT', name: 'Italy', flag: '🇮🇹' },
  { code: 'ES', name: 'Spain', flag: '🇪🇸' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦' },
  { code: 'AU', name: 'Australia', flag: '🇦🇺' },
  { code: 'BR', name: 'Brazil', flag: '🇧🇷' },
  { code: 'IN', name: 'India', flag: '🇮🇳' },
  { code: 'CN', name: 'China', flag: '🇨🇳' },
  { code: 'KR', name: 'South Korea', flag: '🇰🇷' },
  { code: 'MX', name: 'Mexico', flag: '🇲🇽' },
  { code: 'NL', name: 'Netherlands', flag: '🇳🇱' },
  { code: 'SE', name: 'Sweden', flag: '🇸🇪' },
  { code: 'NO', name: 'Norway', flag: '🇳🇴' },
  { code: 'DK', name: 'Denmark', flag: '🇩🇰' },
  { code: 'FI', name: 'Finland', flag: '🇫🇮' },
  { code: 'CH', name: 'Switzerland', flag: '🇨🇭' },
  { code: 'TR', name: 'Türkiye', flag: '🇹🇷' },
  { code: 'RU', name: 'Russia', flag: '🇷🇺' },
  { code: 'EG', name: 'Egypt', flag: '🇪🇬' }
];

// Multilingual content examples showcasing international support
export const multilingualTricks = [
  {
    id: 'tr-1',
    title: 'Çay Demleme Sanatı',
    description: 'Türk çayının mükemmel demlenmesi için geleneksel yöntem',
    steps: ['Çaydanlığı ısıtın', 'Çay yapraklarını ekleyin', '15 dakika demleyin'],
    countryCode: 'TR',
    languageCode: 'tr',
    tags: ['çay', 'türk', 'içecek'],
    authorName: 'Mehmet Özkan',
    difficulty: 'easy' as const
  },
  {
    id: 'jp-1',
    title: '完璧な寿司飯の作り方',
    description: '日本の伝統的な寿司飯の準備方法',
    steps: ['米を洗う', '適切な水加減', '酢飯を作る'],
    countryCode: 'JP',
    languageCode: 'ja',
    tags: ['寿司', '米', '日本料理'],
    authorName: '田中博',
    difficulty: 'medium' as const
  },
  {
    id: 'fr-1',
    title: 'Technique de Pâtisserie Française',
    description: 'Méthode traditionnelle pour réussir la pâte feuilletée',
    steps: ['Préparer la détrempe', 'Incorporer le beurre', 'Plier et tourner'],
    countryCode: 'FR',
    languageCode: 'fr',
    tags: ['pâtisserie', 'français', 'technique'],
    authorName: 'Marie Dubois',
    difficulty: 'hard' as const
  },
  {
    id: 'hi-1',
    title: 'परफेक्ट चाय बनाने की विधि',
    description: 'भारतीय मसाला चाय बनाने की पारंपरिक विधि',
    steps: ['पानी उबालें', 'मसाले डालें', 'चाय पत्ती और दूध मिलाएं'],
    countryCode: 'IN',
    languageCode: 'hi',
    tags: ['चाय', 'भारतीय', 'मसाला'],
    authorName: 'राज शर्मा',
    difficulty: 'easy' as const
  },
  {
    id: 'pt-1',
    title: 'Segredo do Café Brasileiro',
    description: 'Método tradicional para preparar o café perfeito',
    steps: ['Escolha grãos frescos', 'Moa na hora', 'Use água filtrada'],
    countryCode: 'BR',
    languageCode: 'pt',
    tags: ['café', 'brasileiro', 'bebida'],
    authorName: 'Carlos Silva',
    difficulty: 'medium' as const
  },
  {
    id: 'ar-1',
    title: 'طريقة تحضير الكنافة',
    description: 'الطريقة التقليدية لتحضير الكنافة المصرية',
    steps: ['تحضير العجينة', 'إضافة الحشوة', 'الخبز والتقديم'],
    countryCode: 'EG',
    languageCode: 'ar',
    tags: ['حلويات', 'مصري', 'كنافة'],
    authorName: 'أحمد محمد',
    difficulty: 'hard' as const
  },
  {
    id: 'ru-1',
    title: 'Секрет русского борща',
    description: 'Традиционный рецепт приготовления борща',
    steps: ['Подготовить овощи', 'Сварить бульон', 'Добавить свеклу'],
    countryCode: 'RU',
    languageCode: 'ru',
    tags: ['борщ', 'русская кухня', 'суп'],
    authorName: 'Анна Петрова',
    difficulty: 'medium' as const
  },
  {
    id: 'zh-1',
    title: '完美饺子制作法',
    description: '中国传统饺子的制作技巧',
    steps: ['和面', '调馅', '包饺子'],
    countryCode: 'CN',
    languageCode: 'zh',
    tags: ['饺子', '中式', '传统'],
    authorName: '李明',
    difficulty: 'medium' as const
  }
];

export const mockTricks = [
  {
    id: '1',
    title: 'Quick Microwave Cleaning',
    description: 'Clean your microwave in 2 minutes with just water and lemon',
    steps: ['Put lemon slices in water bowl', 'Microwave for 2 minutes', 'Wipe clean easily'],
    countryCode: 'US',
    languageCode: 'en',
    tags: ['cleaning', 'kitchen', 'quick'],
    authorName: 'Sarah Chen',
    kudos: 234,
    views: 1250,
    favorites: 89,
    comments: 23,
    difficulty: 'easy' as const,
    timeEstimate: '2 minutes',
    status: 'approved' as const,
    createdAt: '2024-10-01T10:00:00Z'
  },
  {
    id: '2',
    title: 'Perfect Rice Every Time',
    description: 'Japanese method for fluffy rice without rice cooker',
    steps: ['Rinse rice 3 times', 'Use 1:1.2 rice to water ratio', 'Simmer 18 minutes, rest 10'],
    countryCode: 'JP',
    languageCode: 'ja',
    tags: ['cooking', 'rice', 'japanese'],
    authorName: 'Hiroshi Tanaka',
    kudos: 456,
    views: 2100,
    favorites: 156,
    comments: 67,
    difficulty: 'medium' as const,
    timeEstimate: '30 minutes',
    status: 'approved' as const,
    createdAt: '2024-09-28T14:30:00Z'
  },
  {
    id: '3',
    title: 'Remove Wine Stains Instantly',
    description: 'German grandmother\'s secret for wine stain removal',
    steps: ['Blot immediately', 'Pour salt generously', 'Add club soda and blot'],
    countryCode: 'DE',
    languageCode: 'de',
    tags: ['cleaning', 'stains', 'emergency'],
    authorName: 'Emma Schmidt',
    kudos: 189,
    views: 890,
    favorites: 67,
    comments: 34,
    difficulty: 'easy' as const,
    timeEstimate: '5 minutes',
    status: 'approved' as const,
    createdAt: '2024-09-25T16:45:00Z'
  },
  {
    id: '4',
    title: 'Productivity Pomodoro Hack',
    description: 'French twist on the Pomodoro technique for better focus',
    steps: ['Work 25 min with classical music', 'Take 5 min walk break', 'Repeat 4 cycles, long break'],
    countryCode: 'FR',
    languageCode: 'fr',
    tags: ['productivity', 'focus', 'work'],
    authorName: 'Marie Dubois',
    kudos: 312,
    views: 1680,
    favorites: 98,
    comments: 45,
    difficulty: 'medium' as const,
    timeEstimate: '2 hours',
    status: 'approved' as const,
    createdAt: '2024-09-30T09:15:00Z'
  },
  {
    id: '5',
    title: 'Tea Brewing Perfection',
    description: 'British method for the perfect cup of tea',
    steps: ['Warm the pot first', 'Add tea, then boiling water', 'Steep 3-5 minutes, milk last'],
    countryCode: 'GB',
    languageCode: 'en',
    tags: ['tea', 'british', 'drinks'],
    authorName: 'James Wilson',
    kudos: 278,
    views: 1340,
    favorites: 112,
    comments: 56,
    difficulty: 'easy' as const,
    timeEstimate: '10 minutes',
    status: 'approved' as const,
    createdAt: '2024-09-27T11:20:00Z'
  },
  {
    id: '6',
    title: 'Pasta Water Magic',
    description: 'Italian secret: save pasta water for perfect sauce',
    steps: ['Reserve 1 cup pasta water before draining', 'Add gradually to sauce', 'Creates silky texture'],
    countryCode: 'IT',
    languageCode: 'it',
    tags: ['cooking', 'pasta', 'italian'],
    authorName: 'Marco Rossi',
    kudos: 567,
    views: 2890,
    favorites: 234,
    comments: 89,
    difficulty: 'easy' as const,
    timeEstimate: '15 minutes',
    status: 'approved' as const,
    createdAt: '2024-10-02T18:30:00Z'
  },
  {
    id: '7',
    title: 'Siesta Power Nap',
    description: 'Spanish technique for the perfect afternoon nap',
    steps: ['Nap between 1-3 PM', 'Set alarm for 20 minutes max', 'Dark room, cool temperature'],
    countryCode: 'ES',
    languageCode: 'es',
    tags: ['sleep', 'health', 'energy'],
    authorName: 'Carlos Rodriguez',
    kudos: 145,
    views: 780,
    favorites: 45,
    comments: 23,
    difficulty: 'easy' as const,
    timeEstimate: '20 minutes',
    status: 'approved' as const,
    createdAt: '2024-09-26T15:00:00Z'
  },
  {
    id: '8',
    title: 'Winter Car Defrost',
    description: 'Canadian trick to defrost car windows instantly',
    steps: ['Mix 2:1 water to vinegar', 'Spray on frozen windows', 'Ice melts immediately'],
    countryCode: 'CA',
    languageCode: 'en',
    tags: ['winter', 'car', 'ice'],
    authorName: 'Alex Johnson',
    kudos: 89,
    views: 456,
    favorites: 34,
    comments: 12,
    difficulty: 'easy' as const,
    timeEstimate: '3 minutes',
    status: 'approved' as const,
    createdAt: '2024-09-24T07:45:00Z'
  },
  {
    id: '9',
    title: 'Sunscreen Application',
    description: 'Australian method for proper sun protection',
    steps: ['Apply 30 min before sun', 'Use 1 teaspoon per body part', 'Reapply every 2 hours'],
    countryCode: 'AU',
    languageCode: 'en',
    tags: ['health', 'sun', 'protection'],
    authorName: 'Emma Thompson',
    kudos: 167,
    views: 923,
    favorites: 78,
    comments: 34,
    difficulty: 'easy' as const,
    timeEstimate: '5 minutes',
    status: 'approved' as const,
    createdAt: '2024-09-29T12:00:00Z'
  },
  {
    id: '10',
    title: 'Coffee Bean Storage',
    description: 'Brazilian barista secret for fresh coffee',
    steps: ['Store in airtight container', 'Keep at room temperature', 'Use within 2 weeks of roasting'],
    countryCode: 'BR',
    languageCode: 'pt',
    tags: ['coffee', 'storage', 'fresh'],
    authorName: 'Lucas Silva',
    kudos: 203,
    views: 1120,
    favorites: 89,
    comments: 45,
    difficulty: 'easy' as const,
    timeEstimate: '1 minute',
    status: 'approved' as const,
    createdAt: '2024-10-03T08:15:00Z'
  },
  {
    id: '11',
    title: 'Spice Organization System',
    description: 'Indian kitchen organization for 50+ spices',
    steps: ['Group by cuisine type', 'Label with expiry dates', 'Store in alphabetical order'],
    countryCode: 'IN',
    languageCode: 'hi',
    tags: ['organization', 'spices', 'kitchen'],
    authorName: 'Priya Sharma',
    kudos: 134,
    views: 678,
    favorites: 56,
    comments: 28,
    difficulty: 'medium' as const,
    timeEstimate: '1 hour',
    status: 'approved' as const,
    createdAt: '2024-09-23T14:20:00Z'
  },
  {
    id: '12',
    title: 'Green Tea Ceremony',
    description: 'Chinese method for mindful tea preparation',
    steps: ['Heat water to 80°C', 'Rinse tea leaves first', 'Steep 2-3 minutes maximum'],
    countryCode: 'CN',
    languageCode: 'zh',
    tags: ['tea', 'mindfulness', 'ceremony'],
    authorName: 'Li Wei',
    kudos: 298,
    views: 1456,
    favorites: 123,
    comments: 67,
    difficulty: 'medium' as const,
    timeEstimate: '15 minutes',
    status: 'approved' as const,
    createdAt: '2024-09-22T16:30:00Z'
  },
  {
    id: '13',
    title: 'Kimchi Storage Hack',
    description: 'Korean method to keep kimchi fresh longer',
    steps: ['Press down to remove air bubbles', 'Keep brine above vegetables', 'Store in glass container'],
    countryCode: 'KR',
    languageCode: 'ko',
    tags: ['fermentation', 'storage', 'korean'],
    authorName: 'Kim Min-jun',
    kudos: 176,
    views: 834,
    favorites: 67,
    comments: 34,
    difficulty: 'easy' as const,
    timeEstimate: '5 minutes',
    status: 'approved' as const,
    createdAt: '2024-09-21T13:45:00Z'
  },
  {
    id: '14',
    title: 'Avocado Ripening Trick',
    description: 'Mexican technique to ripen avocados overnight',
    steps: ['Wrap in newspaper with banana', 'Place in warm spot', 'Check after 24 hours'],
    countryCode: 'MX',
    languageCode: 'es',
    tags: ['fruit', 'ripening', 'food'],
    authorName: 'Sofia Martinez',
    kudos: 245,
    views: 1234,
    favorites: 98,
    comments: 45,
    difficulty: 'easy' as const,
    timeEstimate: '24 hours',
    status: 'approved' as const,
    createdAt: '2024-09-20T10:00:00Z'
  },
  {
    id: '15',
    title: 'Bike Maintenance Quick Check',
    description: 'Dutch cycling culture: weekly bike check routine',
    steps: ['Check tire pressure', 'Test brakes and gears', 'Lubricate chain if needed'],
    countryCode: 'NL',
    languageCode: 'nl',
    tags: ['cycling', 'maintenance', 'transport'],
    authorName: 'Jan van Berg',
    kudos: 123,
    views: 567,
    favorites: 45,
    comments: 23,
    difficulty: 'easy' as const,
    timeEstimate: '10 minutes',
    status: 'approved' as const,
    createdAt: '2024-09-19T09:30:00Z'
  },
  {
    id: '16',
    title: 'Sauna Etiquette & Benefits',
    description: 'Swedish sauna tradition for health and relaxation',
    steps: ['Shower before entering', 'Sit on towel', 'Stay 10-15 minutes max'],
    countryCode: 'SE',
    languageCode: 'sv',
    tags: ['health', 'relaxation', 'tradition'],
    authorName: 'Erik Andersson',
    kudos: 189,
    views: 890,
    favorites: 67,
    comments: 34,
    difficulty: 'easy' as const,
    timeEstimate: '30 minutes',
    status: 'approved' as const,
    createdAt: '2024-09-18T17:00:00Z'
  },
  {
    id: '17',
    title: 'Salmon Preparation',
    description: 'Norwegian method for perfect salmon every time',
    steps: ['Remove pin bones with tweezers', 'Salt 15 minutes before cooking', 'Cook skin-side down first'],
    countryCode: 'NO',
    languageCode: 'no',
    tags: ['cooking', 'fish', 'norwegian'],
    authorName: 'Astrid Hansen',
    kudos: 267,
    views: 1345,
    favorites: 112,
    comments: 56,
    difficulty: 'medium' as const,
    timeEstimate: '25 minutes',
    status: 'approved' as const,
    createdAt: '2024-09-17T12:15:00Z'
  },
  {
    id: '18',
    title: 'Hygge Home Atmosphere',
    description: 'Danish concept of creating cozy home environment',
    steps: ['Dim warm lighting', 'Add soft textures', 'Light candles, play soft music'],
    countryCode: 'DK',
    languageCode: 'da',
    tags: ['home', 'cozy', 'atmosphere'],
    authorName: 'Mads Nielsen',
    kudos: 156,
    views: 723,
    favorites: 89,
    comments: 23,
    difficulty: 'easy' as const,
    timeEstimate: '15 minutes',
    status: 'approved' as const,
    createdAt: '2024-09-16T19:30:00Z'
  },
  {
    id: '19',
    title: 'Forest Bathing Technique',
    description: 'Finnish nature therapy for stress relief',
    steps: ['Find quiet forest spot', 'Breathe deeply for 5 minutes', 'Touch trees, listen to sounds'],
    countryCode: 'FI',
    languageCode: 'fi',
    tags: ['nature', 'stress', 'mindfulness'],
    authorName: 'Aino Virtanen',
    kudos: 198,
    views: 967,
    favorites: 78,
    comments: 34,
    difficulty: 'easy' as const,
    timeEstimate: '30 minutes',
    status: 'approved' as const,
    createdAt: '2024-09-15T11:00:00Z'
  },
  {
    id: '20',
    title: 'Chocolate Tempering',
    description: 'Swiss technique for perfect chocolate shine',
    steps: ['Heat to 50°C, cool to 27°C', 'Reheat to 31°C for dark chocolate', 'Test on parchment paper'],
    countryCode: 'CH',
    languageCode: 'de',
    tags: ['chocolate', 'baking', 'technique'],
    authorName: 'Hans Mueller',
    kudos: 234,
    views: 1123,
    favorites: 145,
    comments: 67,
    difficulty: 'hard' as const,
    timeEstimate: '45 minutes',
    status: 'approved' as const,
    createdAt: '2024-09-14T15:45:00Z'
  }
];
